version: '3.1'
services:
  arbeitszeit-frontend:
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - '80:80'
    environment:
      APP_API: https://arbeitszeitapi.app.danielr1996.de
      APP_OAUTH_URL: https://sso.app.danielr1996.de/realms/arbeitszeit
      APP_OAUTH_CLIENT_ID: arbeitszeit-frontend

